### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by khusika**
bionic/libc/bionic/__stpcpy_chk.cpp:54: error: undefined reference to 'stpcpy'

### CODE REVIEW

**Comment by xboxfanj** [comment]
Hey man, what device and soc has this error? I know krait chips work fine.

**Comment by khusika** [comment]
I'm working for Qualcomm Snapdragon MSM8255T (Ancora & Ariesve) devices. I'm not working with EOS but with BlissPop ( https://github.com/TeamBliss-LP ) because it used this bionic.
Hi @Jackeagle can you take a look with this one? :/

**Comment by xboxfanj** [comment]
Figured that was the issue.  You have the scorpion SOC, which is not officially supported by either AOSP or CAF, which means I need to add support for stpcpy manually.  I'll push that in a bit.

**Comment by xboxfanj** [comment]
Grab this http://review.teameos.org/#/c/1895 to fix scorpion.

**Comment by khusika** [comment]
Ok, Thanks sir :+1:

**Pull request closed without merging**
